version: '3'

services:
  influxdb:
    image: tutum/influxdb
    ports:
      - 8083:8083
      - 8086:8086
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    depends_on:
      - influxdb
  books-api:
    container_name: books-api
    build:
      context: .
      dockerfile: books-api-dockerfile
    image: books-api:latest
    ports:
      - 8080:8080
    depends_on:
      - influxdb
  countries-api:
    container_name: countries-api
    build:
      context: .
      dockerfile: countries-api-dockerfile
    image: countries-api:latest
    ports:
      - 8081:8081
    depends_on:
      - influxdb
