version: '3'

services:
  influxdb:
    image: influxdb
    volumes:
      - ./docker/influxdb/data:/var/lib/influxdb
    ports:
      - 8086:8086
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    depends_on:
      - influxdb