version: '3'

services:
  influxdb:
    image: tutum/influxdb
    ports:
      - 8083:8083
      - 8086:8086
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    depends_on:
      - influxdb