spring:
  application:
    name: books-service
  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
  zipkin:
      base-url: http://192.168.1.6:9411/
  sleuth:
    sampler:
      percentage: 1
    web:
      skip-pattern: /health|/info

server:
  context-path: /books-api

endpoints:
  trace:
    sensitive: false

countries-api:
  base-url: http://192.168.1.6:9090/countries-api
  endpoints:
    countries: /countries/

management:
  metrics:
    web:
      server:
        auto-time-requests: true
    export:
      influx:
        uri: http://192.168.1.6:8086
        db: books-api
        step: 5s
        auto-create-db: true
    distribution:
      percentiles[http.server.requests]: 1
      percentiles-histogram[http.server.requests]: true
      sla[http.server.requests]: 10ms, 100ms, 500ms, 1000ms, 2000ms, 5000ms

logging:
  level:
    org.springframework.web.servlet.DispatcherServlet: DEBUG