spring:
  application:
    name: books-service
  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
server:
  context-path: /books-api
endpoints:
  trace:
    sensitive: false
management:
  metrics:
    web:
      server:
        auto-time-requests: true
    export:
      influx:
        uri: http://192.168.1.6:8086
        db: books-api
        step: 5s
        auto-create-db: true
    distribution:
      percentiles[http.server.requests]: 0.5, 0.75, 0.95, 0.99
      percentiles-histogram[http.server.requests]: true
      sla[http.server.requests]: 10ms, 100ms, 500ms, 1000ms, 2000ms, 5000ms