spring:
  application:
    name: books-service
  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
server:
  context-path: /books-api
endpoints:
  trace:
    sensitive: false
management:
  metrics:
    export:
      influx:
        uri: http://localhost:8086
        db: books-api
        step: 5s
        auto-create-db: true
    distribution:
      percentiles[http.server.requests]: 0.95, 0.99
      percentiles-histogram[http.server.requests]: true
      sla[http.server.requests]: 10ms, 100ms