spring:
  application:
    name: gateway
server:
  port: 9090
zuul:
  routes:
    books-api:
      path: /books-api/**
      url: http://192.168.1.6:8080/books-api
    countries-api:
      path: /countries-api/**
      url: http://192.168.1.6:8081/countries-api