spring:
  application:
    name: gateway
  zipkin:
    base-url: http://192.168.1.6:9411/
  sleuth:
    sampler:
      percentage: 1
    web:
      skip-pattern: /health|/info

server:
  port: 9090

zuul:
  routes:
    books-api:
      path: /books-api/**
      url: http://192.168.1.6:8080/books-api
    countries-api:
      path: /countries-api/**
      url: http://192.168.1.6:8081/countries-api

logging:
  level:
    org.springframework.web.servlet.DispatcherServlet: DEBUG
  file: gateway.log