{
 "title": "Microservices monitor",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Up Since",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "format": "dtdurationms",
   "valueName": "current",
   "targets": [
    {
     "measurement": "process.uptime",
     "query": "SELECT \"value\" FROM \"process.uptime\" WHERE (\"host\" = 'Blaze') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "Blaze" }
     ]
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "system.cpu.usage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ " *100" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "API's CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 7, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "process.cpu.usage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ " *100" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Number of CPUs",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "system.cpu.count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Http Requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host$tag_uri",
     "groupBy": [
      { "params": [ "uri" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "http.server.requests",
     "query": "SELECT \"count\" FROM \"http.server.requests\" WHERE $timeFilter GROUP BY \"uri\", \"host\"",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Average HTTP Requests Response Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "dtdurationms" }
   ],
   "targets": [
    {
     "alias": "$tag_host$tag_uri",
     "groupBy": [
      { "params": [ "uri" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "http.server.requests",
     "query": "SELECT \"count\", \"mean\" FROM \"http.server.requests\" WHERE $timeFilter GROUP BY \"uri\"",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "JVM Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "jvm.memory.used",
     "query": "SELECT \"count\", \"mean\" FROM \"http.server.requests\" WHERE $timeFilter GROUP BY \"uri\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "JVM Live Threads",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "jvm.threads.live",
     "query": "SELECT \"count\", \"mean\" FROM \"http.server.requests\" WHERE $timeFilter GROUP BY \"uri\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}