spring:
  application:
    name: countries-service
  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
  zipkin:
      base-url: http://localhost:9411/
  sleuth:
    sampler:
      percentage: 1

server:
  context-path: /countries-api
  port: 8081

endpoints:
  trace:
    sensitive: false

logging:
  level:
    org.springframework.web.servlet.DispatcherServlet: DEBUG
